{
 "title": "Overmind",
 "tags": [ "screeps" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "colonies", "label": "Colonies", "query": "screeps.muon.colonies.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(movingAverage(screeps.muon.cpu.getUsed, 5), #B)",
     "targetFull": "asPercent(movingAverage(screeps.muon.cpu.getUsed, 5), screeps.muon.cpu.limit)"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "screeps.muon.cpu.bucket" }
   ]
  },
  {
   "title": "CPU/Bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.muon.cpu.getUsed, 'CPU')"
    },
    {
     "target": "alias(screeps.muon.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(movingAverage(screeps.muon.cpu.getUsed, 100), 'Average CPU')"
    },
    {
     "target": "alias(screeps.muon.cpu.limit, 'Limit')"
    }
   ]
  },
  { "title": "GCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(screeps.muon.gcl.progress, #B)"
    }
   ]
  },
  {
   "title": "Time to next GCL",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "format": "d",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Rem')",
     "targetFull": "alias(divideSeries(alias(keepLastValue(diffSeries(screeps.muon.gcl.progressTotal, screeps.muon.gcl.progress)), 'Progress to go'), alias(scale(movingAverage(perSecond(keepLastValue(screeps.muon.gcl.progress)), 500), 86400), 'GCL / 24hr (avg)')), 'Rem')"
    }
   ]
  },
  {
   "title": "GCL Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(screeps.muon.gcl.progress)), 10), 86400), 'GCL / 24hr')"
    },
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(screeps.muon.gcl.progress)), 500), 86400), 'GCL / 24hr (avg)')"
    }
   ]
  },
  { "title": "Colonies Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "rooms" },
  {
   "title": "GCL by Colony",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scale(movingAverage(perSecond(keepLastValue(screeps.muon.colonies.$colonies.rcl.progress)), 3600), 86400)), 3)"
    }
   ]
  },
  {
   "title": "RCL Progress Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(movingAverage(perSecond(keepLastValue(screeps.muon.colonies.$colonies.rcl.progress)), 200), 86400), 3)"
    }
   ]
  },
  {
   "title": "Hatchery Uptime",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(screeps.muon.colonies.$colonies.hatchery.uptime), 3)"
    }
   ]
  },
  {
   "title": "Energy in Storage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(screeps.muon.colonies.$colonies.storage.energy), 3)"
    }
   ]
  }
 ]
}