{
 "title": "Overmind",
 "tags": [ "screeps" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "User", "query": "screeps.*" },
   { "name": "colonies", "label": "Colonies", "query": "screeps.$User.colonies.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(movingAverage(screeps.$User.cpu.getUsed, 5), #B)",
     "targetFull": "asPercent(movingAverage(screeps.$User.cpu.getUsed, 5), screeps.$User.cpu.limit)"
    }
   ]
  },
  {
   "title": "CPU/Bucket",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.$User.cpu.getUsed, 'CPU')"
    },
    {
     "target": "alias(movingAverage(screeps.$User.cpu.getUsed, 100), 'Average CPU')"
    },
    {
     "target": "alias(screeps.$User.cpu.limit, 'Limit')"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "screeps.$User.cpu.bucket" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "movingAverage(screeps.$User.memory.used, 5)"
    }
   ]
  },
  { "title": "GCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "GCL Progress",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(screeps.$User.gcl.progress, #B)",
     "targetFull": "asPercent(screeps.$User.gcl.progress, screeps.$User.gcl.progressTotal)"
    }
   ]
  },
  {
   "title": "Expansion Ranking",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "screeps.$User.leaderboard.rank" }
   ]
  },
  {
   "title": "GCL Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(screeps.$User.gcl.progress, 100)), 10), 86400), 'GCL / 24hr')"
    },
    {
     "target": "alias(scale(movingAverage(perSecond(keepLastValue(screeps.$User.gcl.progress, 100)), 500), 86400), 'GCL / 24hr (avg)')"
    }
   ]
  },
  {
   "title": "Time to next GCL",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 18 },
   "format": "d",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Rem')",
     "targetFull": "alias(divideSeries(alias(keepLastValue(diffSeries(screeps.$User.gcl.progressTotal, screeps.$User.gcl.progress)), 'Progress to go'), alias(scale(movingAverage(perSecond(keepLastValue(screeps.$User.gcl.progress)), 500), 86400), 'GCL / 24hr (avg)')), 'Rem')"
    }
   ]
  },
  { "title": "Colonies Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "rooms" },
  {
   "title": "GCL by Colony",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scale(movingAverage(perSecond(keepLastValue(screeps.$User.colonies.$colonies.rcl.progress, 100)), 3600), 86400)), 3)"
    }
   ]
  },
  {
   "title": "RCL Progress Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(movingAverage(perSecond(keepLastValue(screeps.$User.colonies.$colonies.rcl.progress)), 200), 86400), 3)"
    }
   ]
  },
  {
   "title": "Hatchery Uptime",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(screeps.$User.colonies.$colonies.hatchery.uptime), 3)"
    }
   ]
  },
  {
   "title": "Energy in Storage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(screeps.$User.colonies.$colonies.storage.energy), 3)"
    }
   ]
  },
  { "title": "Terminal Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Energy Transfer Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 45 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*))), 86400), 200)"
    }
   ]
  },
  {
   "title": "Incoming Energy Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 45 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 7, 'sumSeries'))), 500), 86000)), 0)"
    }
   ]
  },
  {
   "title": "Outgoing Energy Rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 45 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sortByTotal(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 6, 'sumSeries'))), 500), 86000)), 0)"
    }
   ]
  },
  {
   "title": "Fractional Energy Transfer Cost",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "target": "divideSeries(#A, #B)",
     "targetFull": "divideSeries(movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(screeps.$User.persistent.terminalNetwork.transfers.costs.*.*))), 86400), 200), movingAverage(scaleToSeconds(perSecond(keepLastValue(sumSeries(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*))), 86400), 200))"
    }
   ]
  },
  {
   "title": "Incoming Energy per 24h",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 7, 'sumSeries'))), 200), 86000), 0)"
    }
   ]
  },
  {
   "title": "Outgoing Energy per 24h",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(movingAverage(perSecond(keepLastValue(groupByNode(screeps.$User.persistent.terminalNetwork.transfers.energy.*.*, 6, 'sumSeries'))), 200), 86000), 0)"
    }
   ]
  }
 ]
}